apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gateway # REPLACE ME
  namespace: flux-system
spec:
  image: registry.lognes.dev/microservices/gateway # REPLACE ME
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gateway-policy # REPLACE ME
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gateway # REPLACE ME (WITH IMAGE REPO NAME ABOVE)
  filterTags:
    pattern: '^master-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc