apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-ms # REPLACE ME
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-ms # REPLACE ME
  template:
    metadata:
      labels:
        app: template-ms # REPLACE ME
    spec:
      containers:
      - name: template # REPLACE ME
        image: registry.lognes.dev/microservices/template:master-1729271420 # {"$imagepolicy": "flux-system:template-policy"}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: delve-cm
