apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-ms
  template:
    metadata:
      labels:
        app: template-ms
    spec:
      containers:
      - name: template
        image: registry.lognes.dev/microservices/template:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080