apiVersion: v1
kind: Service
metadata:
  name: template-ms-svc
  namespace: default
spec:
  selector:
    app: template-ms
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080