# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: template-ms-vs # REPLACE ME
  namespace: default
spec:
  hosts:
  - delve.lognes.dev
  gateways:
  - delve-gateway
  http:
  - match:
    - uri:
        exact: "/template" # REPLACE ME
    - uri:
        prefix: "/template/" # REPLACE ME
    rewrite:
      uri: "/"
    route:
    - destination:
        host: template-ms-svc # REPLACE ME