apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: microservices
  namespace: flux-system
spec:
  interval: 5m
  path: "./../../../microservices"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
resources:
- gotk-components.yaml
- gotk-sync.yaml
